### ISSUE TITLE
直接启动程序，无法进入后台

### ISSUE THREAD

**Issue by franklydog** [zh-five/xdaemon#1]
使用这个库之后，编译好，直接双击启动程序，cmd窗口仍然还在。没有进入后台进程。

**Comment by zh-five** [comment]
此库针对的是命令行启动方式（cmd、PowerShell或shell中启动go程序）让程序后台运行不占用命令终端的标准输入输出。windows下直接双击启动并期望隐藏cmd窗口，这似乎是另外一个问题。可以参考一下这篇[博文](https://www.ctolib.com/topics-6902.html)
单纯使用go能否解决这个问题，我还不确定，以后我研究一下。

**Comment by zh-five** [comment]
此库隐藏了子程序的cmd窗口，但双击启动时父级程序默认会显示一个cmd窗口。若要隐藏此窗口，编译时需增加` -ldflags="-H windowsgui" `参数 如：
```bat
go build -ldflags="-H windowsgui" background.go
```
