### ISSUE TITLE
重复打开文件

### ISSUE THREAD

**Issue by kiyonlin** [zh-five/xdaemon#2]
这里的[打开文件](https://github.com/zh-five/xdaemon/blob/master/daemon.go#L127-L133)代码，可能会重复调用，会不会有问题呢？

**Comment by zh-five** [comment]
非常感谢你的反馈，这是一个问题。父进程和子进程同时写日志到同一个问题，是可能造成日志混乱。这需要优化，请问你有什么建议吗？

**Comment by kiyonlin** [comment]
进程结束的时候关闭文件句柄应该就可以了吧

**Comment by zh-five** [comment]
似乎还是会有问题，当以守护进程方式运行时。守护进程和业务进程是同时运行的，可能会同时写日志。
目前最简单的解决方案是守护进程和业务进程分别写不一样的日志文件。

不过多进程写同一个日志文件，怎么避免日志混乱的问题，挺有趣的，以后好好研究一下

**Comment by kiyonlin** [comment]
只要有`os.O_APPEND`标识，内核会处理好各个进程写入磁盘的问题，不会相互覆盖。
